DROP TABLE IF EXISTS data CASCADE;


CREATE TABLE data_carte(
    id_data int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un_text text
);


INSERT INTO data_carte (un_text) VALUES ('Bonjour de la base de données :)');